// AUTO-GENERATED by scraper/scraper/fetch_logos.py — do not edit by hand.
export const GENERATED_SCHOOL_ICONS: Record<string, string> = {
  'chicago-booth': '/school-icons/chicago-booth.jpg',
  'ucla-anderson': '/school-icons/ucla-anderson.svg',
  wharton: '/school-icons/wharton.jpeg',
};
