import os
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup

# Several university sites serve a degraded shell to non-browser agents, so use
# a real browser UA when fetching their HTML (mirrors scraper.fetch.BROWSER_UA).
BROWSER_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# Slugs with hand-curated logos in MANUAL_OVERRIDES (web/lib/schoolIcons.ts).
# The fetch never downloads or regenerates entries for these.
MANUAL_OVERRIDE_SLUGS = {
    "wharton",
    "chicago-booth",
    "ucla-anderson",
    "unc-kenan-flagler",
    # Hand-picked for schools the automated fetch couldn't source.
    "utdallas-jindal",
    "uw-foster",
    "penn-state-smeal",
    "rsm-erasmus",
    "mcgill-desautels",
    "uconn-business",
    "miami-business",
    "houston-bauer",
    "south-carolina-moore",
    "ustc-som",
    "uc-irvine-merage",
    "bocconi-sda",
    "frankfurt-school",
}

_CONTENT_TYPE_EXT = {
    "image/png": ".png",
    "image/jpeg": ".jpg",
    "image/jpg": ".jpg",
    "image/svg+xml": ".svg",
    "image/x-icon": ".ico",
    "image/vnd.microsoft.icon": ".ico",
    "image/webp": ".webp",
    "image/gif": ".gif",
}


def domain_from_url(url: str) -> str:
    return urlparse(url).netloc


def _parse_max_size(sizes: str | None) -> int:
    if not sizes:
        return 0
    best = 0
    for token in sizes.split():
        if "x" in token.lower():
            try:
                w, h = token.lower().split("x")
                best = max(best, int(w) * int(h))
            except ValueError:
                continue
    return best


def extract_icon_url(html: str, base_url: str) -> str | None:
    """Return the best icon URL declared in the page, or None.

    Prefers apple-touch-icon links, then any rel=icon link, ranking by largest
    declared size. Unsized links rank last (area 0) but are still returned if
    they are the only candidate. Resolves relative hrefs against base_url.
    """
    soup = BeautifulSoup(html, "html.parser")
    candidates = []  # (is_apple, area, absolute_url)
    for link in soup.find_all("link"):
        rels = [r.lower() for r in (link.get("rel") or [])]
        href = link.get("href")
        if not href or not rels:
            continue
        is_apple = any("apple-touch-icon" in r for r in rels)
        is_icon = "icon" in rels
        if not (is_apple or is_icon):
            continue
        area = _parse_max_size(link.get("sizes"))
        candidates.append((is_apple, area, urljoin(base_url, href)))
    if not candidates:
        return None
    # Apple-touch-icons first, then largest declared area.
    candidates.sort(key=lambda c: (c[0], c[1]), reverse=True)
    return candidates[0][2]


def favicon_fallback_url(domain: str) -> str:
    return f"https://www.google.com/s2/favicons?domain={domain}&sz=128"


def extension_for(content_type: str, url: str) -> str:
    ct = (content_type or "").split(";")[0].strip().lower()
    if ct in _CONTENT_TYPE_EXT:
        return _CONTENT_TYPE_EXT[ct]
    suffix = Path(urlparse(url).path).suffix.lower()
    return suffix if suffix in {".png", ".jpg", ".jpeg", ".svg", ".ico", ".webp", ".gif"} else ".png"


def render_generated_map(slug_to_filename: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by scraper/scraper/fetch_logos.py — do not edit by hand.",
        "export const GENERATED_SCHOOL_ICONS: Record<string, string> = {",
    ]
    for slug in sorted(slug_to_filename):
        lines.append(f"  '{slug}': '/school-icons/{slug_to_filename[slug]}',")
    lines.append("};")
    return "\n".join(lines) + "\n"


REQUEST_HEADERS = {"User-Agent": BROWSER_UA, "Accept-Language": "en-US,en;q=0.9"}
MIN_IMAGE_BYTES = 512  # anything smaller is almost certainly broken/empty
ICON_DIR = Path(__file__).resolve().parent.parent.parent / "web" / "public" / "school-icons"
GENERATED_TS = Path(__file__).resolve().parent.parent.parent / "web" / "lib" / "schoolIcons.generated.ts"


def _download(url: str) -> tuple[bytes, str] | None:
    try:
        resp = requests.get(url, headers=REQUEST_HEADERS, timeout=30)
        resp.raise_for_status()
    except requests.RequestException:
        return None
    ct = resp.headers.get("Content-Type", "")
    if "image" not in ct and not url.lower().endswith((".png", ".jpg", ".jpeg", ".svg", ".ico")):
        return None
    if len(resp.content) < MIN_IMAGE_BYTES:
        return None
    return resp.content, ct


def fetch_one(slug: str, website_url: str) -> tuple[str, str] | None:
    """Fetch, validate, and save one school's logo.

    Returns (filename, source) where source is 'site' or 'favicon', or None on
    failure. Never touches MANUAL_OVERRIDE_SLUGS.
    """
    domain = domain_from_url(website_url)
    icon_url = None
    try:
        page = requests.get(website_url, headers=REQUEST_HEADERS, timeout=30)
        page.raise_for_status()
        icon_url = extract_icon_url(page.text, website_url)
    except requests.RequestException:
        pass

    source = "site"
    result = _download(icon_url) if icon_url else None
    if result is None:
        source = "favicon"
        result = _download(favicon_fallback_url(domain))
    if result is None:
        return None

    content, content_type = result
    used_url = icon_url if source == "site" else favicon_fallback_url(domain)
    filename = f"{slug}{extension_for(content_type, used_url)}"
    ICON_DIR.mkdir(parents=True, exist_ok=True)
    # Remove any stale file for this slug (extension may have changed on --force).
    for stale in ICON_DIR.glob(f"{slug}.*"):
        stale.unlink()
    (ICON_DIR / filename).write_bytes(content)
    return filename, source


def _existing_map() -> dict[str, str]:
    """slug -> filename for icons already on disk."""
    mapping = {}
    if ICON_DIR.exists():
        for path in ICON_DIR.iterdir():
            if path.is_file() and not path.name.startswith("."):
                mapping[path.stem] = path.name
    return mapping


def fetch_school_logos(supabase, force: bool = False) -> None:
    rows = supabase.table("schools").select("slug,website_url").execute().data
    existing = _existing_map()
    results = {"site": 0, "favicon": 0, "failed": [], "skipped": 0}

    for row in rows:
        slug, website_url = row["slug"], row.get("website_url")
        if slug in MANUAL_OVERRIDE_SLUGS or not website_url:
            results["skipped"] += 1
            continue
        if not force and slug in existing:
            results["skipped"] += 1
            continue
        outcome = fetch_one(slug, website_url)
        if outcome is None:
            results["failed"].append(slug)
            print(f"  FAIL   {slug}")
        else:
            filename, source = outcome
            results[source] += 1
            print(f"  {source:7} {slug} -> {filename}")

    # Regenerate the TS map from whatever is now on disk.
    final_map = _existing_map()
    GENERATED_TS.write_text(render_generated_map(final_map), encoding="utf-8")

    print(
        f"\nDone. site={results['site']} favicon={results['favicon']} "
        f"failed={len(results['failed'])} skipped={results['skipped']}"
    )
    if results["failed"]:
        print("Failed slugs:", ", ".join(results["failed"]))


def main() -> None:
    import sys

    from supabase import create_client

    client = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_ROLE_KEY"])
    fetch_school_logos(client, force="--force" in sys.argv)


if __name__ == "__main__":
    main()
