import os
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup

# Several university sites serve a degraded shell to non-browser agents, so use
# a real browser UA when fetching their HTML (mirrors scraper.fetch.BROWSER_UA).
BROWSER_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# Slugs with hand-curated logos in MANUAL_OVERRIDES (web/lib/schoolIcons.ts).
# The fetch never downloads or regenerates entries for these.
MANUAL_OVERRIDE_SLUGS = {"wharton", "chicago-booth", "ucla-anderson", "unc-kenan-flagler"}

_CONTENT_TYPE_EXT = {
    "image/png": ".png",
    "image/jpeg": ".jpg",
    "image/jpg": ".jpg",
    "image/svg+xml": ".svg",
    "image/x-icon": ".ico",
    "image/vnd.microsoft.icon": ".ico",
    "image/webp": ".webp",
    "image/gif": ".gif",
}


def domain_from_url(url: str) -> str:
    return urlparse(url).netloc


def _parse_max_size(sizes: str | None) -> int:
    if not sizes:
        return 0
    best = 0
    for token in sizes.split():
        if "x" in token.lower():
            try:
                w, h = token.lower().split("x")
                best = max(best, int(w) * int(h))
            except ValueError:
                continue
    return best


def extract_icon_url(html: str, base_url: str) -> str | None:
    """Return the best icon URL declared in the page, or None.

    Prefers apple-touch-icon links, then any rel=icon with a size, choosing the
    largest declared size. Resolves relative hrefs against base_url.
    """
    soup = BeautifulSoup(html, "html.parser")
    candidates = []  # (is_apple, area, absolute_url)
    for link in soup.find_all("link"):
        rels = [r.lower() for r in (link.get("rel") or [])]
        href = link.get("href")
        if not href or not rels:
            continue
        is_apple = any("apple-touch-icon" in r for r in rels)
        is_icon = "icon" in rels or "shortcut" in rels
        if not (is_apple or is_icon):
            continue
        area = _parse_max_size(link.get("sizes"))
        candidates.append((is_apple, area, urljoin(base_url, href)))
    if not candidates:
        return None
    # Apple-touch-icons first, then largest declared area.
    candidates.sort(key=lambda c: (c[0], c[1]), reverse=True)
    return candidates[0][2]


def favicon_fallback_url(domain: str) -> str:
    return f"https://www.google.com/s2/favicons?domain={domain}&sz=128"


def extension_for(content_type: str, url: str) -> str:
    ct = (content_type or "").split(";")[0].strip().lower()
    if ct in _CONTENT_TYPE_EXT:
        return _CONTENT_TYPE_EXT[ct]
    suffix = Path(urlparse(url).path).suffix.lower()
    return suffix if suffix in {".png", ".jpg", ".jpeg", ".svg", ".ico", ".webp", ".gif"} else ".png"


def render_generated_map(slug_to_filename: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by scraper/scraper/fetch_logos.py — do not edit by hand.",
        "export const GENERATED_SCHOOL_ICONS: Record<string, string> = {",
    ]
    for slug in sorted(slug_to_filename):
        lines.append(f"  '{slug}': '/school-icons/{slug_to_filename[slug]}',")
    lines.append("};")
    return "\n".join(lines) + "\n"
